### ISSUE TITLE
Access Violation When Running Example

### ISSUE THREAD

**Issue by Pebaz** [thgcode/pytcc#1]
The example: `/test/testrun.py` fails with an access violation exception.

Running on:

* Windows 10 x64
* Intel i5 2.4GHz
* 16.0 GB RAM
* Python 3.7.1 AMD64
* TCC 0.9.27 x86_64

```c
from pytcc import TCC
comp = TCC()
comp.preprocessor_symbols["DEBUG"] = "1"
comp.add_library_path("./")
comp.add_file("test.c")
comp.compile_string('''
int main(int argc, char **argv)
    {
    printf("%s %d", argv[0], sum(2, 2));
    return 0;
}
''')
comp.run(["test"])
```

### Error Message:

```
Traceback (most recent call last):
  File "C:\Users\samuel.wilder\Desktop\__jit2__.py", line 13, in <module>
    comp.run(["test"])
  File "C:\Python37\lib\site-packages\pytcc\tcc.py", line 158, in run
    return self._run(c_argc, c_argv)
  File "C:\Python37\lib\site-packages\pytcc\tcc.py", line 30, in f
    result = func(*args, **kw)
  File "C:\Python37\lib\site-packages\pytcc\tcc.py", line 146, in _run
    return lib.tcc_run(self.state, argc, argv)
OSError: exception: access violation writing 0x00000000FFC000EC
```

**Comment by thgcode** [comment]
Thank you for the bug report.
I am trying to fix it for the latest TCC version. It gave the same error on my Windows 7 computer.
In the meantime, can you test if this same error occurs with the libtcc.dll I put in the pytcc directory of the project? This library is from TCC 0.9.26.

**Comment by Pebaz** [comment]
I have tried it with the 0.9.26 DLL from TCC and it gives this error:

```
pytcc.tcc.Error: Error in _run: -1: tcc: error: undefined symbol 'printf'
```

When I manually add `include "stdio.h"` to the example, it silently crashes (no error).

**Comment by thgcode** [comment]
I pushed a commit with some changes to the defines of the output type constants. Can you test if it works with your TCC 0.9.27 version?

**Comment by Pebaz** [comment]
Worked!

Output:
```
Sum 2 2
```

Thank you so much!  Have a great rest of week!
